-- Current sql file was generated after introspecting the database
-- If you want to run this migration please uncomment this code before executing migrations
/*
CREATE TYPE "public"."dupinsession" AS ENUM('RETAIN', 'REMOVE', 'UNIQUE');--> statement-breakpoint
CREATE TYPE "public"."existingtype" AS ENUM('NEW', 'EXISTING');--> statement-breakpoint
CREATE TYPE "public"."finalstatus" AS ENUM('ACCEPTED', 'REJECTED', 'PENDING');--> statement-breakpoint
CREATE TYPE "public"."finalvalidatedstatus" AS ENUM('VALIDATED', 'NOT_VALIDATED', 'NOT_REQUIRED', 'PENDING', 'FAILED', 'AUTO_REJECT', 'AUTO_ACCEPT', 'REVIEW');--> statement-breakpoint
CREATE TYPE "public"."groupintervals" AS ENUM('HOUR', 'DAY', 'WEEK', 'MONTH', 'QUARTER', 'YEAR');--> statement-breakpoint
CREATE TYPE "public"."notificationtype" AS ENUM('UPDATE', 'ALERT', 'RATING_CHANGE');--> statement-breakpoint
CREATE TYPE "public"."oribismatchstatus" AS ENUM('MATCH', 'NO_MATCH', 'PENDING');--> statement-breakpoint
CREATE TYPE "public"."periodicsessiontype" AS ENUM('NEW SESSION', 'RETRY SESSION', 'SKIPPED');--> statement-breakpoint
CREATE TYPE "public"."sourceenum" AS ENUM('NU', 'OD', 'CM', 'PD');--> statement-breakpoint
CREATE TYPE "public"."status" AS ENUM('NOT_STARTED', 'STARTED', 'IN_PROGRESS', 'COMPLETED', 'FAILED', 'PENDING', 'QUEUED', 'SKIP', 'SKIPPED', 'ACTIVE', 'INACTIVE');--> statement-breakpoint
CREATE TYPE "public"."truesightstatus" AS ENUM('VALIDATED', 'NOT_VALIDATED', 'NOT_REQUIRED', 'PENDING', 'NO_MATCH');--> statement-breakpoint
CREATE TYPE "public"."validationstatus" AS ENUM('VALIDATED', 'NOT_VALIDATED', 'PENDING');--> statement-breakpoint
CREATE SEQUENCE "public"."users_table_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1;--> statement-breakpoint
CREATE TABLE "fstb" (
	"id" serial PRIMARY KEY NOT NULL,
	"kpi_area" varchar NOT NULL,
	"kpi_code" varchar NOT NULL,
	"kpi_flag" boolean NOT NULL,
	"kpi_value" varchar,
	"kpi_details" varchar,
	"ens_id" varchar NOT NULL,
	"session_id" varchar NOT NULL,
	"kpi_rating" varchar,
	"kpi_definition" varchar,
	"create_time" timestamp with time zone DEFAULT now() NOT NULL,
	"update_time" timestamp with time zone DEFAULT now() NOT NULL,
	"kpi_data" jsonb,
	CONSTRAINT "unique_ensid_session_kpifstb" UNIQUE("kpi_code","ens_id","session_id")
);
--> statement-breakpoint
CREATE TABLE "lgrk" (
	"id" serial PRIMARY KEY NOT NULL,
	"kpi_area" varchar NOT NULL,
	"kpi_code" varchar NOT NULL,
	"kpi_flag" boolean NOT NULL,
	"kpi_value" varchar,
	"kpi_details" varchar,
	"ens_id" varchar NOT NULL,
	"session_id" varchar NOT NULL,
	"kpi_rating" varchar,
	"kpi_definition" varchar,
	"create_time" timestamp with time zone DEFAULT now() NOT NULL,
	"update_time" timestamp with time zone DEFAULT now() NOT NULL,
	"kpi_data" jsonb,
	CONSTRAINT "unique_ensid_session_kpilgrk" UNIQUE("kpi_code","ens_id","session_id")
);
--> statement-breakpoint
CREATE TABLE "ensid_screening_status" (
	"id" serial PRIMARY KEY NOT NULL,
	"session_id" varchar(50) NOT NULL,
	"ens_id" varchar(50),
	"overall_status" "status" DEFAULT 'NOT_STARTED' NOT NULL,
	"orbis_retrieval_status" "status" DEFAULT 'NOT_STARTED' NOT NULL,
	"screening_modules_status" "status" DEFAULT 'NOT_STARTED' NOT NULL,
	"report_generation_status" "status" DEFAULT 'NOT_STARTED' NOT NULL,
	"create_time" timestamp with time zone DEFAULT now() NOT NULL,
	"update_time" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "unique_ensid_session_ensid_screening_status" UNIQUE("session_id","ens_id")
);
--> statement-breakpoint
CREATE TABLE "grid_management" (
	"id" serial PRIMARY KEY NOT NULL,
	"session_id" varchar(50) NOT NULL,
	"ens_id" varchar(50),
	"contact_id" varchar,
	"grid_adverse_media_other_crimes" jsonb,
	"grid_adverse_media_reputational_risk" jsonb,
	"grid_sanctions" jsonb,
	"grid_regulatory" jsonb,
	"grid_bribery_fraud_corruption" jsonb,
	"grid_pep" jsonb,
	"grid_legal" jsonb,
	"create_time" timestamp with time zone DEFAULT now() NOT NULL,
	"update_time" timestamp with time zone DEFAULT now() NOT NULL,
	"management_info" jsonb,
	CONSTRAINT "unique_management_id" UNIQUE("session_id","ens_id","contact_id")
);
--> statement-breakpoint
CREATE TABLE "ens_schedule_group_mapping" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "ens_schedule_group_mapping_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"ens_id" varchar NOT NULL,
	"group_id" varchar NOT NULL,
	"create_time" timestamp with time zone DEFAULT now() NOT NULL,
	"update_time" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "cyes" (
	"id" serial PRIMARY KEY NOT NULL,
	"kpi_area" varchar NOT NULL,
	"kpi_code" varchar NOT NULL,
	"kpi_flag" boolean NOT NULL,
	"kpi_value" varchar,
	"kpi_details" varchar,
	"ens_id" varchar NOT NULL,
	"session_id" varchar NOT NULL,
	"kpi_rating" varchar,
	"kpi_definition" varchar,
	"create_time" timestamp with time zone DEFAULT now() NOT NULL,
	"update_time" timestamp with time zone DEFAULT now() NOT NULL,
	"kpi_data" jsonb,
	CONSTRAINT "unique_ensid_session_kpicyes" UNIQUE("kpi_code","ens_id","session_id")
);
--> statement-breakpoint
CREATE TABLE "alembic_version" (
	"version_num" varchar(32) PRIMARY KEY NOT NULL
);
--> statement-breakpoint
CREATE TABLE "news_master" (
	"id" serial PRIMARY KEY NOT NULL,
	"link" text,
	"name" varchar NOT NULL,
	"title" text,
	"category" text,
	"summary" text,
	"news_date" date,
	"sentiment" varchar,
	"content_filtered" boolean,
	"country" text,
	"create_time" timestamp with time zone DEFAULT now() NOT NULL,
	"update_time" timestamp with time zone DEFAULT now() NOT NULL,
	"start_date" date,
	"end_date" date,
	"error" text,
	CONSTRAINT "unique_name_link_date" UNIQUE("link","name","news_date")
);
--> statement-breakpoint
CREATE TABLE "entity_universe" (
	"id" integer GENERATED BY DEFAULT AS IDENTITY (sequence name "entity_universe_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"ens_id" varchar(50) PRIMARY KEY NOT NULL,
	"bvd_id" varchar(50),
	"name" varchar(255),
	"name_international" varchar(255),
	"address" text,
	"postcode" varchar(20),
	"city" varchar(100),
	"country" varchar(100),
	"phone_or_fax" varchar(50),
	"email_or_website" varchar(100),
	"national_id" varchar(50),
	"state" varchar(100),
	"address_type" varchar(50),
	"last_session_id" varchar(50),
	"overall_supplier_rating" varchar(50),
	"thematic_rating" jsonb,
	"management" jsonb,
	"unmodified_name" varchar(255),
	"unmodified_name_international" varchar(255),
	"unmodified_address" text,
	"unmodified_postcode" varchar(20),
	"unmodified_city" varchar(100),
	"unmodified_country" varchar(100),
	"unmodified_phone_or_fax" varchar(50),
	"unmodified_email_or_website" varchar(100),
	"unmodified_national_id" varchar(50),
	"unmodified_state" varchar(100),
	"unmodified_address_type" varchar(50),
	"last_screened_date" timestamp with time zone,
	"external_vendor_id" varchar,
	"create_time" timestamp with time zone DEFAULT now() NOT NULL,
	"update_time" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "oval" (
	"id" serial PRIMARY KEY NOT NULL,
	"kpi_area" varchar NOT NULL,
	"kpi_code" varchar NOT NULL,
	"kpi_flag" boolean NOT NULL,
	"kpi_value" varchar,
	"kpi_details" varchar,
	"ens_id" varchar NOT NULL,
	"session_id" varchar NOT NULL,
	"kpi_rating" varchar,
	"kpi_definition" varchar,
	"create_time" timestamp with time zone DEFAULT now() NOT NULL,
	"update_time" timestamp with time zone DEFAULT now() NOT NULL,
	"kpi_data" jsonb,
	CONSTRAINT "unique_ensid_session_kpioval" UNIQUE("kpi_code","ens_id","session_id")
);
--> statement-breakpoint
CREATE TABLE "report_plot" (
	"id" serial PRIMARY KEY NOT NULL,
	"session_id" varchar(50) NOT NULL,
	"ens_id" varchar(50),
	"sentiment_aggregation" jsonb,
	"create_time" timestamp with time zone DEFAULT now() NOT NULL,
	"update_time" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "sown" (
	"id" serial PRIMARY KEY NOT NULL,
	"kpi_area" varchar NOT NULL,
	"kpi_code" varchar NOT NULL,
	"kpi_flag" boolean NOT NULL,
	"kpi_value" varchar,
	"kpi_details" varchar,
	"ens_id" varchar NOT NULL,
	"session_id" varchar NOT NULL,
	"kpi_rating" varchar,
	"kpi_definition" varchar,
	"create_time" timestamp with time zone DEFAULT now() NOT NULL,
	"update_time" timestamp with time zone DEFAULT now() NOT NULL,
	"kpi_data" jsonb,
	CONSTRAINT "unique_ensid_session_kpisown" UNIQUE("kpi_code","ens_id","session_id")
);
--> statement-breakpoint
CREATE TABLE "supplier_master_data" (
	"id" serial PRIMARY KEY NOT NULL,
	"name" varchar(255),
	"name_international" varchar(255),
	"address" text,
	"postcode" varchar(20),
	"city" varchar(100),
	"country" varchar(100),
	"phone_or_fax" varchar(50),
	"email_or_website" varchar(100),
	"national_id" varchar(50),
	"state" varchar(100),
	"ens_id" varchar(50),
	"session_id" varchar(50) NOT NULL,
	"bvd_id" varchar(50) NOT NULL,
	"validation_status" "validationstatus" DEFAULT 'PENDING' NOT NULL,
	"final_status" "finalstatus" DEFAULT 'PENDING' NOT NULL,
	"create_time" timestamp with time zone DEFAULT now() NOT NULL,
	"update_time" timestamp with time zone DEFAULT now() NOT NULL,
	"report_generation_status" "status" DEFAULT 'NOT_STARTED' NOT NULL,
	"external_vendor_id" varchar,
	"uploaded_name" varchar(255),
	"existing_entity" "existingtype",
	CONSTRAINT "supplier_master_ensid_session" UNIQUE("ens_id","session_id")
);
--> statement-breakpoint
CREATE TABLE "grid_pm_tracking" (
	"id" integer GENERATED BY DEFAULT AS IDENTITY (sequence name "grid_pm_tracking_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"grid_tracking_id" varchar,
	"category" varchar,
	"grid_enquiry_id" varchar,
	"primary_id" varchar PRIMARY KEY NOT NULL,
	"create_time" timestamp with time zone DEFAULT now() NOT NULL,
	"update_time" timestamp with time zone DEFAULT now() NOT NULL,
	"name" text
);
--> statement-breakpoint
CREATE TABLE "rfct" (
	"id" serial PRIMARY KEY NOT NULL,
	"kpi_area" varchar NOT NULL,
	"kpi_code" varchar NOT NULL,
	"kpi_flag" boolean NOT NULL,
	"kpi_value" varchar,
	"kpi_details" varchar,
	"ens_id" varchar NOT NULL,
	"session_id" varchar NOT NULL,
	"kpi_rating" varchar,
	"kpi_definition" varchar,
	"create_time" timestamp with time zone DEFAULT now() NOT NULL,
	"update_time" timestamp with time zone DEFAULT now() NOT NULL,
	"kpi_data" jsonb,
	CONSTRAINT "unique_ensid_session_kpirfct" UNIQUE("kpi_code","ens_id","session_id")
);
--> statement-breakpoint
CREATE TABLE "user_account" (
	"user_id" uuid PRIMARY KEY NOT NULL,
	"email" varchar(256) NOT NULL,
	"hashed_password" varchar(128) NOT NULL,
	"create_time" timestamp with time zone DEFAULT now() NOT NULL,
	"update_time" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "management_association" (
	"contact_id" varchar PRIMARY KEY NOT NULL,
	"name" varchar,
	"associated_ens_id" varchar[],
	"create_time" timestamp with time zone DEFAULT now() NOT NULL,
	"update_time" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "notification" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "notification_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"ens_id" varchar(50),
	"notification_type" "notificationtype" DEFAULT 'UPDATE' NOT NULL,
	"title" varchar(255),
	"description" text,
	"theme" varchar(100),
	"data_value" text,
	"session_id" varchar(50),
	"create_time" timestamp with time zone DEFAULT now(),
	"update_time" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "schedule_monitoring" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "schedule_monitoring_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"group_id" varchar NOT NULL,
	"group_name" varchar,
	"periodicity" varchar,
	"frequency" integer NOT NULL,
	"interval" "groupintervals" DEFAULT 'WEEK' NOT NULL,
	"start_date" timestamp with time zone,
	"next_run_date" timestamp with time zone,
	"last_scheduled_date" timestamp with time zone,
	"last_start_time" timestamp with time zone,
	"status" "status" DEFAULT 'ACTIVE' NOT NULL,
	"group_description" text,
	"created_by" varchar,
	"create_time" timestamp with time zone DEFAULT now() NOT NULL,
	"update_time" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "schedule_monitoring_group_id_key" UNIQUE("group_id")
);
--> statement-breakpoint
CREATE TABLE "refresh_token" (
	"id" bigserial PRIMARY KEY NOT NULL,
	"refresh_token" varchar(512) NOT NULL,
	"used" boolean NOT NULL,
	"exp" bigint NOT NULL,
	"user_id" varchar,
	"user_group" varchar,
	"create_time" timestamp with time zone DEFAULT now() NOT NULL,
	"update_time" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "summary" (
	"id" serial PRIMARY KEY NOT NULL,
	"session_id" varchar(50) NOT NULL,
	"ens_id" varchar(50),
	"area" varchar(50) NOT NULL,
	"summary" text,
	"create_time" timestamp with time zone DEFAULT now() NOT NULL,
	"update_time" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "unique_ens_session_summary" UNIQUE("session_id","ens_id","area")
);
--> statement-breakpoint
CREATE TABLE "users_table" (
	"id" serial NOT NULL,
	"user_id" varchar NOT NULL,
	"email" varchar NOT NULL,
	"username" varchar NOT NULL,
	"password" varchar NOT NULL,
	"verified" boolean NOT NULL,
	"otp" varchar,
	"user_group" varchar NOT NULL,
	"create_time" timestamp with time zone DEFAULT now() NOT NULL,
	"update_time" timestamp with time zone DEFAULT now() NOT NULL,
	"api_key" varchar NOT NULL,
	"key_expires_at" timestamp,
	CONSTRAINT "uq_users_table_user_id" UNIQUE("user_id"),
	CONSTRAINT "users_table_api_key_key" UNIQUE("api_key")
);
--> statement-breakpoint
CREATE TABLE "orgdata" (
	"id" serial PRIMARY KEY NOT NULL,
	"orgname" varchar(100) NOT NULL,
	"orgidentifier" varchar(100) NOT NULL,
	"bvdids" varchar(100),
	"created_at" timestamp DEFAULT now(),
	CONSTRAINT "orgdata_orgidentifier_key" UNIQUE("orgidentifier"),
	CONSTRAINT "orgdata_bvdids_key" UNIQUE("bvdids")
);
--> statement-breakpoint
CREATE TABLE "matchbvdid" (
	"bvdid" varchar(255) NOT NULL,
	"name" varchar(255),
	"name_international" varchar(255),
	"address" text,
	"postcode" varchar(50),
	"city" varchar(255),
	"country" varchar(255),
	"phone_or_fax" varchar(255),
	"email_or_website" varchar(255),
	"national_id" varchar(255),
	"state" varchar(255),
	"address_type" varchar(255),
	"ens_id" varchar(255) PRIMARY KEY NOT NULL
);
--> statement-breakpoint
CREATE TABLE "client_configuration" (
	"id" serial PRIMARY KEY NOT NULL,
	"client_id" varchar(50) NOT NULL,
	"client_name" varchar(250),
	"kpi_theme" varchar(50),
	"report_section" varchar(50),
	"kpi_area" varchar NOT NULL,
	"module_enabled_status" boolean NOT NULL,
	"create_time" timestamp with time zone DEFAULT now() NOT NULL,
	"update_time" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "unique_client_configuration" UNIQUE("client_id","client_name","kpi_theme","report_section","kpi_area")
);
--> statement-breakpoint
CREATE TABLE "session_configuration" (
	"id" serial PRIMARY KEY NOT NULL,
	"session_id" varchar(50) NOT NULL,
	"module" varchar(50),
	"module_active_status" boolean NOT NULL,
	"create_time" timestamp with time zone DEFAULT now() NOT NULL,
	"update_time" timestamp with time zone DEFAULT now() NOT NULL,
	"client_id" varchar(50) NOT NULL,
	CONSTRAINT "unique_session_configuration" UNIQUE("session_id","module")
);
--> statement-breakpoint
CREATE TABLE "session_group_mapping" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "session_group_mapping_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"session_id" varchar,
	"group_id" varchar,
	"source_id" varchar,
	"mapping_type" "periodicsessiontype" DEFAULT 'NEW SESSION' NOT NULL,
	"create_time" timestamp with time zone DEFAULT now() NOT NULL,
	"update_time" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "excluded_entities" (
	"id" serial PRIMARY KEY NOT NULL,
	"name" varchar(100),
	"category" text,
	"create_time" timestamp with time zone DEFAULT now() NOT NULL,
	"update_time" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "external_supplier_data" (
	"id" serial PRIMARY KEY NOT NULL,
	"roe_using_net_income" jsonb,
	"event_adverse_media_other_crimes" jsonb,
	"event_adverse_media_reputational_risk" jsonb,
	"legal" jsonb,
	"solvency_ratio" jsonb,
	"roce_before_tax" jsonb,
	"roe_before_tax" jsonb,
	"profit_margin" jsonb,
	"shareholders_fund" jsonb,
	"total_assets" jsonb,
	"cash_flow" jsonb,
	"pl_before_tax" jsonb,
	"beneficial_owners_intermediatory" jsonb,
	"controlling_shareholders" jsonb,
	"grid_event_sanctions" jsonb,
	"grid_event_regulatory" jsonb,
	"grid_event_bribery_fraud_corruption" jsonb,
	"grid_event_pep" jsonb,
	"grid_event_adverse_media_other_crimes" jsonb,
	"grid_event_adverse_media_reputational_risk" jsonb,
	"grid_legal" jsonb,
	"management" jsonb,
	"no_of_employee" integer,
	"national_identifier_type" jsonb,
	"national_identifier" jsonb,
	"alias" jsonb,
	"incorporation_date" date,
	"num_subsidiaries" integer,
	"num_companies_in_corp_grp" integer,
	"num_direct_shareholders" integer,
	"operating_revenue" jsonb,
	"profit_loss_after_tax" jsonb,
	"ebitda" jsonb,
	"current_ratio" jsonb,
	"pr_qualitative_score_date" date,
	"pr_more_risk_score_date" date,
	"pr_reactive_more_risk_score_date" date,
	"payment_risk_score" numeric,
	"esg_overall_rating" integer,
	"esg_environmental_rating" integer,
	"esg_social_rating" integer,
	"esg_governance_rating" integer,
	"esg_date" date,
	"cyber_risk_score" integer,
	"cyber_date" date,
	"implied_cyber_risk_score_date" date,
	"beneficial_owners" jsonb,
	"global_ultimate_owner" jsonb,
	"shareholders" jsonb,
	"ultimately_owned_subsidiaries" jsonb,
	"other_ultimate_beneficiary" jsonb,
	"event_sanctions" jsonb,
	"event_regulatory" jsonb,
	"event_bribery_fraud_corruption" jsonb,
	"event_pep" jsonb,
	"name" text,
	"country" text,
	"location" text,
	"address" text,
	"is_active" varchar,
	"operation_type" varchar,
	"legal_form" varchar,
	"bvd_id" varchar,
	"pr_reactive_more_risk_score" varchar,
	"cyber_botnet_infection" varchar,
	"cyber_malware_servers" varchar,
	"cyber_ssl_certificate" varchar,
	"cyber_webpage_headers" varchar,
	"website" text,
	"implied_cyber_risk_score" text,
	"ens_id" varchar,
	"controlling_shareholders_type" jsonb,
	"session_id" varchar,
	"cyber_bonet_infection" varchar,
	"global_ultimate_owner_type" jsonb,
	"pr_qualitative_score" varchar,
	"pr_more_risk_score" varchar,
	"pr_more_risk_score_ratio" jsonb,
	"pr_reactive_more_risk_score_ratio" jsonb,
	"create_time" timestamp with time zone DEFAULT now() NOT NULL,
	"update_time" timestamp with time zone DEFAULT now() NOT NULL,
	"long_and_short_term_debt" numeric,
	"long_term_debt" numeric,
	"total_shareholders_equity" numeric,
	"default_events" jsonb,
	"orbis_news" jsonb,
	"operating_revenue_usd" jsonb,
	"event" jsonb,
	"city" varchar(100),
	"postcode" varchar(20),
	CONSTRAINT "unique_ens_session" UNIQUE("ens_id","session_id")
);
--> statement-breakpoint
CREATE TABLE "news" (
	"id" serial PRIMARY KEY NOT NULL,
	"kpi_area" varchar NOT NULL,
	"kpi_code" varchar NOT NULL,
	"kpi_flag" boolean NOT NULL,
	"kpi_value" varchar,
	"kpi_details" varchar,
	"ens_id" varchar NOT NULL,
	"session_id" varchar NOT NULL,
	"kpi_rating" varchar,
	"kpi_definition" varchar,
	"create_time" timestamp with time zone DEFAULT now() NOT NULL,
	"update_time" timestamp with time zone DEFAULT now() NOT NULL,
	"kpi_data" jsonb,
	CONSTRAINT "unique_ensid_session_kpinews" UNIQUE("kpi_code","ens_id","session_id")
);
--> statement-breakpoint
CREATE TABLE "ovar" (
	"id" serial PRIMARY KEY NOT NULL,
	"kpi_area" varchar NOT NULL,
	"kpi_code" varchar NOT NULL,
	"kpi_flag" boolean NOT NULL,
	"kpi_value" varchar,
	"kpi_details" varchar,
	"ens_id" varchar NOT NULL,
	"session_id" varchar NOT NULL,
	"kpi_rating" varchar,
	"kpi_definition" varchar,
	"create_time" timestamp with time zone DEFAULT now() NOT NULL,
	"update_time" timestamp with time zone DEFAULT now() NOT NULL,
	"kpi_data" jsonb,
	CONSTRAINT "unique_ensid_session_kpiovar" UNIQUE("kpi_code","ens_id","session_id")
);
--> statement-breakpoint
CREATE TABLE "sape" (
	"id" serial PRIMARY KEY NOT NULL,
	"kpi_area" varchar NOT NULL,
	"kpi_code" varchar NOT NULL,
	"kpi_flag" boolean NOT NULL,
	"kpi_value" varchar,
	"kpi_details" varchar,
	"ens_id" varchar NOT NULL,
	"session_id" varchar NOT NULL,
	"kpi_rating" varchar,
	"kpi_definition" varchar,
	"create_time" timestamp with time zone DEFAULT now() NOT NULL,
	"update_time" timestamp with time zone DEFAULT now() NOT NULL,
	"kpi_data" jsonb,
	CONSTRAINT "unique_ensid_session_kpisape" UNIQUE("kpi_code","ens_id","session_id")
);
--> statement-breakpoint
CREATE TABLE "session_screening_status" (
	"id" serial PRIMARY KEY NOT NULL,
	"session_id" varchar(50) NOT NULL,
	"overall_status" "status" DEFAULT 'NOT_STARTED' NOT NULL,
	"list_upload_status" "status" DEFAULT 'NOT_STARTED' NOT NULL,
	"supplier_name_validation_status" "status" DEFAULT 'NOT_STARTED' NOT NULL,
	"screening_analysis_status" "status" DEFAULT 'NOT_STARTED' NOT NULL,
	"create_time" timestamp with time zone DEFAULT now() NOT NULL,
	"update_time" timestamp with time zone DEFAULT now() NOT NULL,
	"total_ens_count" integer,
	"completed_ens_count" integer,
	"failed_ens_count" integer,
	"skipped_ens_count" integer,
	"source" "sourceenum" DEFAULT 'NU',
	"source_id" varchar,
	CONSTRAINT "unique_sessionid_session" UNIQUE("session_id")
);
--> statement-breakpoint
CREATE TABLE "webhook_response" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "webhook_response_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"ens_id" varchar(255),
	"session_id" varchar(50),
	"response_id" varchar(100),
	"response_time" timestamp with time zone DEFAULT now(),
	"create_time" timestamp with time zone DEFAULT now() NOT NULL,
	"update_time" timestamp with time zone DEFAULT now() NOT NULL,
	"response" jsonb
);
--> statement-breakpoint
CREATE TABLE "token_monitor" (
	"usage_time" timestamp with time zone DEFAULT now(),
	"token_used" integer NOT NULL,
	"payload" jsonb,
	"openai_model" text,
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "token_monitor_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"create_time" timestamp with time zone DEFAULT now() NOT NULL,
	"update_time" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "api_keys" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "api_keys_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"api_key" varchar NOT NULL,
	"user_id" varchar NOT NULL,
	"is_active" boolean,
	"created_at" timestamp DEFAULT now(),
	"expires_at" timestamp,
	"create_time" timestamp with time zone DEFAULT now() NOT NULL,
	"update_time" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "api_keys_api_key_key" UNIQUE("api_key"),
	CONSTRAINT "api_keys_unique" UNIQUE("api_key","user_id")
);
--> statement-breakpoint
CREATE TABLE "continuous_monitoring" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "continuous_monitoring_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"group_id" varchar NOT NULL,
	"group_name" varchar,
	"create_time" timestamp with time zone DEFAULT now() NOT NULL,
	"update_time" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "continuous_monitoring_group_id_key" UNIQUE("group_id")
);
--> statement-breakpoint
CREATE TABLE "ens_continuous_group_mapping" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "ens_continuous_group_mapping_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"ens_id" varchar(50) NOT NULL,
	"group_id" varchar(50) NOT NULL,
	"status" varchar(50),
	"create_time" timestamp with time zone DEFAULT now() NOT NULL,
	"update_time" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "uq_ens_group" UNIQUE("ens_id","group_id")
);
--> statement-breakpoint
CREATE TABLE "company_profile" (
	"id" serial NOT NULL,
	"name" varchar,
	"location" varchar,
	"address" varchar,
	"website" varchar,
	"active_status" varchar,
	"operation_type" varchar,
	"legal_status" varchar,
	"national_identifier" varchar,
	"alias" text,
	"incorporation_date" varchar,
	"shareholders" text,
	"revenue" varchar,
	"subsidiaries" varchar,
	"corporate_group" varchar,
	"key_executives" text,
	"employee" varchar,
	"session_id" varchar(50) NOT NULL,
	"ens_id" varchar(50) NOT NULL,
	"create_time" timestamp with time zone DEFAULT now() NOT NULL,
	"update_time" timestamp with time zone DEFAULT now() NOT NULL,
	"external_vendor_id" varchar,
	"uploaded_name" varchar(255),
	CONSTRAINT "company_profile_pkey" PRIMARY KEY("session_id","ens_id"),
	CONSTRAINT "unique_ensid_session" UNIQUE("session_id","ens_id")
);
--> statement-breakpoint
CREATE TABLE "upload_supplier_master_data" (
	"id" serial NOT NULL,
	"uploaded_name" varchar,
	"uploaded_name_international" varchar,
	"uploaded_address" text,
	"uploaded_postcode" varchar,
	"uploaded_city" varchar,
	"uploaded_country" varchar,
	"uploaded_phone_or_fax" varchar,
	"uploaded_email_or_website" varchar,
	"uploaded_national_id" varchar,
	"uploaded_state" varchar,
	"uploaded_address_type" varchar,
	"name" varchar,
	"name_international" varchar,
	"address" text,
	"postcode" varchar,
	"city" varchar,
	"country" varchar,
	"phone_or_fax" varchar,
	"email_or_website" varchar,
	"national_id" varchar,
	"state" varchar,
	"address_type" varchar,
	"suggested_name" varchar,
	"suggested_name_international" varchar,
	"suggested_address" text,
	"suggested_postcode" varchar,
	"suggested_city" varchar,
	"suggested_country" varchar,
	"suggested_phone_or_fax" varchar,
	"suggested_email_or_website" varchar,
	"suggested_national_id" varchar,
	"suggested_state" varchar,
	"suggested_address_type" varchar,
	"ens_id" varchar NOT NULL,
	"session_id" varchar NOT NULL,
	"bvd_id" varchar,
	"validation_status" "validationstatus" DEFAULT 'PENDING' NOT NULL,
	"final_status" "finalstatus" DEFAULT 'PENDING' NOT NULL,
	"final_validation_status" "finalvalidatedstatus" DEFAULT 'PENDING' NOT NULL,
	"orbis_matched_status" "oribismatchstatus" DEFAULT 'PENDING' NOT NULL,
	"truesight_status" "truesightstatus" DEFAULT 'PENDING' NOT NULL,
	"matched_percentage" integer NOT NULL,
	"truesight_percentage" integer NOT NULL,
	"suggested_bvd_id" varchar,
	"pre_existing_bvdid" boolean NOT NULL,
	"process_status" "status" DEFAULT 'PENDING' NOT NULL,
	"create_time" timestamp with time zone DEFAULT now() NOT NULL,
	"update_time" timestamp with time zone DEFAULT now() NOT NULL,
	"unmodified_name" varchar,
	"unmodified_name_international" varchar,
	"unmodified_address" text,
	"unmodified_postcode" varchar,
	"unmodified_city" varchar,
	"unmodified_country" varchar,
	"unmodified_phone_or_fax" varchar,
	"unmodified_email_or_website" varchar,
	"unmodified_national_id" varchar,
	"unmodified_state" varchar,
	"unmodified_address_type" varchar,
	"user_id" varchar,
	"uploaded_external_vendor_id" varchar,
	"duplicate_in_session" "dupinsession" DEFAULT 'UNIQUE' NOT NULL,
	"existing_entity" "existingtype",
	CONSTRAINT "upload_supplier_master_data_pkey" PRIMARY KEY("id","ens_id")
);
--> statement-breakpoint
ALTER TABLE "refresh_token" ADD CONSTRAINT "refresh_token_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "public"."users_table"("user_id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "upload_supplier_master_data" ADD CONSTRAINT "upload_supplier_master_data_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "public"."users_table"("user_id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
CREATE UNIQUE INDEX "ix_user_account_email" ON "user_account" USING btree ("email" text_ops);--> statement-breakpoint
CREATE UNIQUE INDEX "ix_refresh_token_refresh_token" ON "refresh_token" USING btree ("refresh_token" text_ops);--> statement-breakpoint
CREATE UNIQUE INDEX "ix_users_table_email" ON "users_table" USING btree ("email" text_ops);--> statement-breakpoint
CREATE INDEX "ix_users_table_id" ON "users_table" USING btree ("id" int4_ops);--> statement-breakpoint
CREATE UNIQUE INDEX "ix_users_table_username" ON "users_table" USING btree ("username" text_ops);
*/